---
- hosts: ios
  gather_facts: no
  connection: local

  vars:
    limit_to: "*"
    debug: false
# Run the tests within blocks allows the the next module to be tested if the previous one fails.
# This is done to allow https://github.com/ansible/dci-partner-ansible/ to run the full set of tests.


  tasks:
    - set_fact:
        test_failed: false
    - block:
      - include_role:
          name: ios_banner
        when: "limit_to in ['*', 'ios_banner']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: ios_command
        when: "limit_to in ['*', 'ios_command']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: ios_config
        when: "limit_to in ['*', 'ios_config']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: ios_facts
        when: "limit_to in ['*', 'ios_facts']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: ios_template
        when: "limit_to in ['*', 'ios_template']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: ios_system
        when: "limit_to in ['*', 'ios_system']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: ios_user
        when: "limit_to in ['*', 'ios_user']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: ios_static_route
        when: "limit_to in ['*', 'ios_static_route']"
      rescue:
        - set_fact: test_failed=true


###########
    - name: Has any previous test failed?
      fail:
        msg: "One or more tests failed, check log for details"
      when: test_failed